apiVersion: v1
kind: Pod
metadata:
  name: unschedulable
  labels:
    name: unschedulable
spec:
  schedulerName: fogatlas
  containers:
  - name: unschedulable
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    resources:
      requests:
        cpu: "0"
        memory: "1Mi"